export const siteConfig = {
  name: "Cloud IPTV",
  logo: "/logo.png",
  tagline: "Premium IPTV Streaming",
  telegramLink: "https://t.me/cloudiptv",
  telegramChannelName: "Cloud IPTV Channel",
  noticeText: "⚡ Welcome to Cloud IPTV. Join our Telegram Channel for updates, new playlists, and exclusive content.",
  noticeLink: "https://t.me/cloudiptv",
  noticeLinkText: "Join Now",
  defaultPlaylistUrl: "https://go.skym3u.top/k98v.m3u",
  accentColor: "#2563EB",
  hoverAccent: "#3B82F6",
  categories: [
    "Sports",
    "News",
    "Movies",
    "Kids",
    "Music",
    "Religious",
    "Entertainment",
    "Bangla",
    "English",
    "Hindi",
  ],
};
